apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: quay-quarkus-1
  janus-idp.io/tekton: quay-quarkus-1
  backstage.io/kubernetes-id: quay-quarkus-1
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: quay-quarkus-1
resources:
- deployment.yaml
- route.yaml
- service.yaml
