apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: quay-quarkus-1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: quay-quarkus-1 
  name: quay-quarkus-1
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: quay-quarkus-1
    weight: 100 
